# Generated by Django 5.0.4 on 2024-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.TextField(default='SOME STRING', max_length=255, verbose_name='название'),
        ),
    ]
