# Generated by Django 5.0.4 on 2024-05-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=255, verbose_name='название'),
        ),
    ]
