# Generated by Django 5.0.4 on 2024-05-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_user_alter_image_name_alter_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
