# Generated by Django 5.0.4 on 2024-05-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desc',
            field=models.CharField(default='SOME STRING', max_length=255, verbose_name='Описание'),
        ),
    ]
